"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.RouteStopItem = exports.RouteStopList = exports.DeleteRouteButton = exports.UpdateRouteButton = exports.RouteButton = exports.RouteDetails = exports.RouteHeader = exports.RouteItem = exports.RouteTitle = exports.RouteContainer = exports.StopDeleteButton = exports.StopListItem = exports.StopList = exports.FormButton = exports.FormSelect = exports.FormInput = exports.FormLabel = exports.FormContainer = void 0;
var styled_components_1 = __importDefault(require("styled-components"));
exports.FormContainer = styled_components_1.default.form(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: flex;\n  flex-direction: column;\n  gap: 20px;\n  background-color: #f9f9f9;\n  padding: 20px;\n  border-radius: 8px;\n  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\n  max-width: 400px;\n  margin: 0 auto;\n"], ["\n  display: flex;\n  flex-direction: column;\n  gap: 20px;\n  background-color: #f9f9f9;\n  padding: 20px;\n  border-radius: 8px;\n  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\n  max-width: 400px;\n  margin: 0 auto;\n"])));
exports.FormLabel = styled_components_1.default.label(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  font-size: 1rem;\n  margin-bottom: 5px;\n  color: #333;\n"], ["\n  font-size: 1rem;\n  margin-bottom: 5px;\n  color: #333;\n"])));
exports.FormInput = styled_components_1.default.input(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  padding: 8px;\n  border-radius: 4px;\n  border: 1px solid #ccc;\n  font-size: 1rem;\n  width: 100%;\n"], ["\n  padding: 8px;\n  border-radius: 4px;\n  border: 1px solid #ccc;\n  font-size: 1rem;\n  width: 100%;\n"])));
exports.FormSelect = styled_components_1.default.select(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  padding: 8px;\n  border-radius: 4px;\n  border: 1px solid #ccc;\n  font-size: 1rem;\n  width: 100%;\n"], ["\n  padding: 8px;\n  border-radius: 4px;\n  border: 1px solid #ccc;\n  font-size: 1rem;\n  width: 100%;\n"])));
exports.FormButton = styled_components_1.default.button(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  padding: 10px;\n  background-color: #4caf50;\n  color: white;\n  border: none;\n  border-radius: 4px;\n  font-size: 1rem;\n  cursor: pointer;\n\n  &:hover {\n    background-color: #45a049;\n  }\n"], ["\n  padding: 10px;\n  background-color: #4caf50;\n  color: white;\n  border: none;\n  border-radius: 4px;\n  font-size: 1rem;\n  cursor: pointer;\n\n  &:hover {\n    background-color: #45a049;\n  }\n"])));
exports.StopList = styled_components_1.default.ul(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  list-style-type: none;\n  padding: 0;\n"], ["\n  list-style-type: none;\n  padding: 0;\n"])));
exports.StopListItem = styled_components_1.default.li(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  background-color: #e7f3e7;\n  padding: 10px;\n  border-radius: 4px;\n  margin-bottom: 10px;\n  font-size: 0.9rem;\n"], ["\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  background-color: #e7f3e7;\n  padding: 10px;\n  border-radius: 4px;\n  margin-bottom: 10px;\n  font-size: 0.9rem;\n"])));
exports.StopDeleteButton = styled_components_1.default.button(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n  background: transparent;\n  border: none;\n  cursor: pointer;\n  margin-left: 10px;\n  display: flex;\n  align-items: center;\n\n  img {\n    width: 16px;\n    height: 16px;\n  }\n"], ["\n  background: transparent;\n  border: none;\n  cursor: pointer;\n  margin-left: 10px;\n  display: flex;\n  align-items: center;\n\n  img {\n    width: 16px;\n    height: 16px;\n  }\n"])));
exports.RouteContainer = styled_components_1.default.div(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n  margin-top: 20px;\n  padding: 20px;\n  background-color: #f9f9f9;\n  border-radius: 8px;\n  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\n"], ["\n  margin-top: 20px;\n  padding: 20px;\n  background-color: #f9f9f9;\n  border-radius: 8px;\n  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\n"])));
exports.RouteTitle = styled_components_1.default.h3(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n  text-align: center;\n  color: #333;\n"], ["\n  text-align: center;\n  color: #333;\n"])));
exports.RouteItem = styled_components_1.default.div(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n  margin-bottom: 15px;\n  padding: 10px;\n  border: 1px solid #ddd;\n  border-radius: 4px;\n  background-color: #fff;\n  transition: background-color 0.3s;\n\n  &:hover {\n    background-color: #f1f1f1;\n  }\n"], ["\n  margin-bottom: 15px;\n  padding: 10px;\n  border: 1px solid #ddd;\n  border-radius: 4px;\n  background-color: #fff;\n  transition: background-color 0.3s;\n\n  &:hover {\n    background-color: #f1f1f1;\n  }\n"])));
exports.RouteHeader = styled_components_1.default.h4(templateObject_12 || (templateObject_12 = __makeTemplateObject(["\n  color: #007bff;\n"], ["\n  color: #007bff;\n"])));
exports.RouteDetails = styled_components_1.default.p(templateObject_13 || (templateObject_13 = __makeTemplateObject(["\n  font-size: 14px;\n  color: #666;\n"], ["\n  font-size: 14px;\n  color: #666;\n"])));
exports.RouteButton = styled_components_1.default.button(templateObject_14 || (templateObject_14 = __makeTemplateObject(["\n  padding: 8px 12px;\n  margin-right: 10px;\n  border: none;\n  border-radius: 4px;\n  cursor: pointer;\n  font-weight: bold;\n  transition: background-color 0.3s, color 0.3s;\n\n  &:hover {\n    filter: brightness(0.9);\n  }\n"], ["\n  padding: 8px 12px;\n  margin-right: 10px;\n  border: none;\n  border-radius: 4px;\n  cursor: pointer;\n  font-weight: bold;\n  transition: background-color 0.3s, color 0.3s;\n\n  &:hover {\n    filter: brightness(0.9);\n  }\n"])));
exports.UpdateRouteButton = (0, styled_components_1.default)(exports.RouteButton)(templateObject_15 || (templateObject_15 = __makeTemplateObject(["\n  background-color: #4caf50; \n  color: white;\n  margin-top: 10px; \n\n  &:hover {\n    background-color: #45a049; \n  }\n"], ["\n  background-color: #4caf50; \n  color: white;\n  margin-top: 10px; \n\n  &:hover {\n    background-color: #45a049; \n  }\n"])));
exports.DeleteRouteButton = (0, styled_components_1.default)(exports.RouteButton)(templateObject_16 || (templateObject_16 = __makeTemplateObject(["\n  background-color: #f44336;\n  color: white;\n  margin-top: 10px; \n\n  &:hover {\n    background-color: #e53935;\n  }\n"], ["\n  background-color: #f44336;\n  color: white;\n  margin-top: 10px; \n\n  &:hover {\n    background-color: #e53935;\n  }\n"])));
exports.RouteStopList = styled_components_1.default.ul(templateObject_17 || (templateObject_17 = __makeTemplateObject(["\n  margin: 5px 0 0 20px;\n"], ["\n  margin: 5px 0 0 20px;\n"])));
exports.RouteStopItem = styled_components_1.default.li(templateObject_18 || (templateObject_18 = __makeTemplateObject(["\n  font-size: 14px;\n  color: #555;\n"], ["\n  font-size: 14px;\n  color: #555;\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11, templateObject_12, templateObject_13, templateObject_14, templateObject_15, templateObject_16, templateObject_17, templateObject_18;
